# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


workspace 'SDKDemo'

def sharepods
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~>3.7'
end

target 'SDKDemo' do
project 'SDKDemo'
sharepods
end
